name: ğŸš€ Deploy to GCP Windows VM (cherang-bot)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Windows VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd "C:\Users\gs554\Desktop\ìë£Œ\ë””ìŠ¤ì½”ë“œ ë´‡\cherang-bot"
            git pull origin main
            pip install -r requirements.txt --upgrade
            pm2 restart cherang
            echo ğŸš€ Deploy complete!
            on:
  schedule:
    - cron: "0 19 * * *"  # í•œêµ­ì‹œê°„ ìƒˆë²½ 4ì‹œ(UTC+9)
  workflow_dispatch:

